### PR TITLE
change browser aliasing to be more explicit

### PR DESCRIPTION
**Pull request by DeMoorJasper**
Related to an issue encountered by a user of parcel: https://github.com/parcel-bundler/parcel/issues/1631

### CODE REVIEW

**Review by bcomnes — APPROVED** [review]
Fair enough. Thanks!

**Comment by bcomnes** [comment]
Tests are failing for some reason.  Will have to dig in before merging.

**Comment by lachenmayer** [comment]
Hey @bcomnes :)
The tests for on-load are actually all passing (20/20), the error in the CI stems from testron. In fact all of the previous releases I've tried out (back to v3.2.0) have the same error.
I've written a fix for it here https://github.com/shama/testron/pull/8
Would really appreciate if you merged this, as it's currently stopping me from using nanocomponent in a project that could really use it.
Thanks! :)

**Comment by bcomnes** [comment]
Ok perfect.  Yeah, will cut a release asap today.

**Comment by bcomnes** [comment]
🎉`on-load@3.4.1`🎉

**Pull request merged**
